# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true

# Parchment mappings used by NeoGradle
neogradle.subsystems.parchment.minecraftVersion=1.21.1
neogradle.subsystems.parchment.mappingsVersion=2024.11.17

# Mantle
mod_version=1.12
mod_id=mantle
mod_name=Mantle
mod_license=MIT
mod_group_id=slimeknights.mantle

# Minecraft / NeoForge
minecraft_version=1.21.1
minecraft_range=[1.21.1]
neo_version=21.1.249
loader_range=[4,)

# Build dependencies
jei_version=19.42.0.380
